app:
  image: golang:1.5.0
  command: ["go", "build"]
  working_dir: '/go/src/github.com/caiguanhao/oss-diff'
  environment:
    - API_PREFIX
    - BUCKET
    - ALIYUN_ACCESS_KEY
    - ALIYUN_ACCESS_SECRET
  volumes:
    - '.:/go/src/github.com/caiguanhao/oss-diff'
